name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_esp32:

    name: build esp32

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - esp32:esp32:XIAO_ESP32C3
        sketch-paths:
          - MidiFilePlayer
          - MidiLivePlayback
        esp32_version:
          - 3.2.1
          - 2.0.17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              version: ${{ matrix.esp32_version }}
          sketch-paths: ${{ matrix.sketch-paths }}
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools
              - source-url: https://github.com/marcel-licence/ML_SynthTools_Lib.git
                name: ML_SynthTools_Lib
              - source-url: https://github.com/Seeed-Studio/Seeed_Arduino_MIDIMaster.git
                name: Seeed_Arduino_MIDIMaster
